fix: sitemap include
Novactive/Nova-eZPlatform-Bundles pull request #135
Opened 2023-07-26 14:11 UTC by Gintron

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Fixed tickets | 

This commit fixes wrong Criterion generation that happened when using sitemap_includes

2023-08-01 08:22 UTC, pspanja commented
Hi @florianalexandre, any chance to get this in soonish?

2023-08-11 14:22 UTC, florianalexandre requested changes

2023-08-11 14:22 UTC, florianalexandre commented on components/SEOBundle/bundle/Core/Sitemap/QueryFactory.php
> +                dd($contentTypeIdentifier);
can you just remove this ?

2023-08-29 07:44 UTC, florianalexandre approved these changes

2023-08-31 09:24 UTC, florianalexandre commented
merge in https://github.com/Novactive/Nova-eZPlatform-Bundles/pull/141
tagged [v7.0.2](https://github.com/Novactive/NovaeZSEOBundle/releases/tag/v7.0.2)

2023-08-31 09:24 UTC, closed without merging