[ADD] IP added under the config file default_settings.yaml are now ab…
Novactive/Nova-eZPlatform-Bundles pull request #24
Opened 2021-01-29 16:06 UTC by Jurdn

…le to access site even under maintenance.

| Q             | A
| ------------- | ---
| Branch?       | master / x.y.z
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no
| Fixed tickets | #23 

Added new feature on MaintenanceBundle to let authorized IP (in default_settings.yml) to connect to the website even if it's in maintenance mode.

Fixed crash when user tries to access admin routes without the /admin prefix by checking user rights. It now redirects to authentication if user is not logged in instead of just crashing.

![image](https://user-images.githubusercontent.com/53064509/106298393-1f7d1c80-6254-11eb-9a9b-069ecac4fbbe.png)

2021-02-02 13:44 UTC, okante reviewed
Can you please make:
services lazy (add lazy: true) to services definitions in service.yml
Use 
```php
public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::REQUEST => [
                ['onKernelRequest', 10],
            ],
        ];
    }
``` 
instead of KernelEvents::RESPONSE,
doing that you should also modif `onKernelRequest` parameter to `Symfony\Component\HttpKernel\Event\RequestEvent;` according to the documentation

2021-11-29 14:46 UTC, okante requested changes

2021-11-29 14:46 UTC, okante commented on components/MaintenanceBundle/bundle/Controller/MaintenanceController.php
> +    public function indexAction(PermissionResolver $permissionResolver): Response
remove permission resolver from hier

2021-11-29 14:46 UTC, okante commented on components/MaintenanceBundle/bundle/Controller/MaintenanceController.php
> +        PermissionResolver $permissionResolver
remove unused permission Resolver

2022-01-06 15:57 UTC, florianalexandre requested changes

2022-01-06 15:57 UTC, florianalexandre commented on components/MaintenanceBundle/bundle/Controller/MaintenanceController.php
>       * @Template("@ezdesign/maintenance/index.html.twig")
not used anymore right ?

2022-01-06 15:57 UTC, florianalexandre commented on components/MaintenanceBundle/bundle/Resources/translations/forms.en.yml
> +role.policy.novamaintenance: 'Maintain'
Maintenance

2022-01-06 16:11 UTC, Plopix approved these changes
Ok with the few changes ;)

2022-01-06 16:11 UTC, Plopix commented on components/MaintenanceBundle/bundle/Controller/MaintenanceController.php
>       * @Template("@ezdesign/maintenance/index.html.twig")
=> template annotation right.

2022-01-06 16:11 UTC, Plopix commented on components/MaintenanceBundle/bundle/NovaeZMaintenanceBundle.php
> +        $eZExtension = $container->getExtension('ezpublish');
Can we double check if this is still `ezpublish`

2022-01-14 12:41 UTC, okante commented on components/MaintenanceBundle/bundle/Resources/translations/forms.en.yml
> +role.policy.novamaintenance: 'Maintain'
Done!

2022-01-17 09:57 UTC, florianalexandre approved these changes

2022-01-21 19:05 UTC, merged